use sqlTestTask;

ALTER TABLE Branches DROP CONSTRAINT FK_Branches_Bank_Id;
ALTER TABLE Clients DROP CONSTRAINT FK_Clients_Status_Id;
ALTER TABLE Accounts DROP CONSTRAINT FK_Accounts_Bank_Id;
ALTER TABLE Accounts DROP CONSTRAINT FK_Accounts_Client_Id;
ALTER TABLE Cards DROP CONSTRAINT FK_Cards_Account_Id;
go
DROP TABLE IF EXISTS Branches;
DROP TABLE IF EXISTS Clients;
DROP TABLE IF EXISTS Accounts;
DROP TABLE IF EXISTS Cards;
DROP TABLE IF EXISTS Cities;
DROP TABLE IF EXISTS Statuses;
DROP TABLE IF EXISTS Banks;
go 
DROP PROCEDURE dbo.Add10ToBalanceBySocialGroup;
DROP PROCEDURE dbo.TransferFromAccountToCard;